# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            "Tkay's"
tagline:          ' Blog'
description:      'Web & Linux workarounds'
url:              http://arunhedcet.github.io

author:
  name:           'Arun Kumar TK'
  url:            https://github.com/arunhedcet

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/arunhedcet/arunhedcet.github.io
